;
; ASSEMBLY OUTPUT FOR: <RAW CODE>
;
; Generated by TINY->ASM compiler
;
; Author David Sverdlov
;
.globl _start
.type _start, @function
_start:
	 call 	 main
	 mov 	 EBX, 0
	 mov 	 EAX, 1
	 int 	 0x80
	 push 	 int		 ; Push int on the stack
	 push 	 a		 ; Push a on the stack
