;
; ASSEMBLY OUTPUT FOR: <RAW CODE>
;
; Generated by TINY->ASM compiler
;
; Author David Sverdlov
;
; Assembled via: nasm.exe -f win32 gen.asm
;
; Linked via: gcc gen.obj driver.c asm_io.obj


%include 'asm_io.inc'
; Initialized data
segment .data
readint db 	"Enter an integer: ", 0
readstr db 	"Enter a string: ", 0
readchar db 	"Enter a char: ", 0
; Uninitialized data
segment .bss
a resd 4

segment .code
	global _asm_main
;
; FUNCTION DECLARATION: void _asm_main () {...}
;
; Offsets for formal parameters
; Offsets for local variables 
%define a ebp-4 		; int a
%define _tmp_1 ebp-8 		; int _tmp_1
; START FUNCTION BODY
_asm_main:
	 enter 	 0,0 		; Routine: push ebp /  mov ebp,esp
	 pusha
	 mov 	 eax, eax
	 mov 	 [_tmp_1], eax 		; _tmp_1 = eax
	 mov 	 eax, [_tmp_1]
	 call 	 print_int
	 popa
	 mov 	 eax, 0 		 ; return back to C
	 leave 		; Routine: mov esp,ebp / pop ebp
	 ret
